### ISSUE TITLE
How to download english-pcedt model?

### ISSUE THREAD

**Issue by lejarx** [UniversalDependencies/UD_English-PCEDT#1]
Hi,

Is this english model available for use?

```
> udpipe_download_model(language = "english-pcedt")
Error in udpipe_download_model(language = "english-pcedt") : 
  Please provide a valid language.
```

**Comment by lejarx** [comment]
I think I figured it out, it's not a publicly available model 
`https://ufal.mff.cuni.cz/~zabokrtsky/publications/slides/2021_april_monday_seminar_corefud.pdf`

If somehow it's possible for me to use it, I would definitely like to know more.

Thanks!

**Comment by dan-zeman** [comment]
There is no model here. This repository might eventually hold a corpus but only if license issues are resolved.
